### ISSUE TITLE
Maybe a new list for the misp-warning-lists? 

### ISSUE THREAD

**Issue by adulau** [davidonzo/Threat-Intel-Domain-WL#1]
It's a good idea and it might be useful for other organisations. What do you think of adding your list as the davidonzo list in the official MISP warning-lists?

**Comment by davidonzo** [comment]
Ciao @adulau,

You know I'm always glad to contribute to MISP project!
Let me fork the MISP Warning-lists repository and I'll try to arrange a PR.

I think I have to make at least some change to the WL generator script.

I let you know ASAP. Thanks for the suggestion.
DB

**Comment by davidonzo** [comment]
PR submitted https://github.com/MISP/misp-warninglists/pull/250
